### PR TITLE
Large refactor

### PR DESCRIPTION
**Pull request by FutureSharks**
- Rewriting to use classes instead of a collection of functions.
- Switching to use camera based motion detection instead of PIR sensor
- Some changes to be thread safe (Locks and Queues)
- Switching to Python 3

### CODE REVIEW

**Comment by liamtill** [comment]
Hi, love this project and have recently played around with it. I wanted motion detection from camera only so added it for testing my self just recently to your 0.7 version. I used OpenCV and have tested with an IP camera. Code i have added/modified works for an IP camera and should work the same for Pi camera and USB camera. I have added it but have not tested it for those yet.

Not sure if its useful for you to use to add into this new version. I see you approach motion detection differently here. 

Thanks
Liam

**Comment by FutureSharks** [comment]
Hi,
Thanks for the message!

I tried a couple of motion detection methods. Some are complicated and some had lots of false positives. In the end the method in this PR came from the author of picamera and it seems to work well and it's simple. I still get occasional false triggers though. I'm hoping to reduce the `motion_detection_setting` after some use to stop that though.

Can you make a gist of your method with openCV? Do you get many false positives?

Thanks,
Max

**Comment by liamtill** [comment]
Hi,

Yeah I've seen some quite complicated ones. I came across the method I've used with OpenCV a few times so used that and made some slight modifications. I saw a similar method where the background average is checked against some average threshold value possibly similar to comparing the magnitude of vectors. The OpenCV method compares the area of contours found in the binary image to a given threshold. 

To be honest i haven't tested it greatly, it appears to work and is based on other examples I've seen that work. I don't have a pi camera and have still to test with the USB camera, so only used an IP camera. Given the code that does the main detection is the same then it should work, only the video source changes. False positives will show up dependent on the thresholds used. Similarly to thresholds with either methods. It does do what i'ts meant to and detects motion/takes photos/gifs.

I have uploaded the files to my fork of your repo for viewing (https://github.com/liamtill/rpi-security). The next step i wanted to take was making the functions added to your code a class and methods, allowing detection from multiple video sources. Making it a class would now conform with your refactor. Maybe something in there may be of use to you, as i mainly did it to save buying a PIR & a pi camera!

Thanks
Liam

**Comment by FutureSharks** [comment]
Hi Liam,
I see, thanks for sharing! Interesting approach. Maybe I'll write some test code based on what you have and compare it to my approach with numpy and PiMotionAnalysis.

One thing that is important for me is to have really no false positives. They annoy me. I might just merge what I have here and tune the motion setting after.

If you come up with a better or more reliable motion detection method then feel free to make a PR :)


Max

**Comment by liamtill** [comment]
Hi Max,
No problem, would be interesting to compare. 

Yeah makes sense, don't want it going off all the time when nothing is there. I'm not sure if adaptive thresholding in OpenCV may be of any use (http://docs.opencv.org/3.2.0/d7/d4d/tutorial_py_thresholding.html). Could help with different lighting conditions in the image. 

May give it a test. Anyway great work with this project and many thanks.

Liam

**Pull request merged**
